Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2021-09, with the labels that each got.

#242 [oracle-cloud] Update common files for branch master
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new_feature.yaml
  .github/ISSUE_TEMPLATE/other.yaml
  .github/workflows/central-sync.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  oraclecloud-sdk-processor/src/main/java/io/micronaut/oraclecloud/clients/processor/OracleCloudSdkProcessor.java
  settings.gradle
Labels: relates-to: build

#265 [oracle-cloud] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#266 SDK reflect config fix
  oraclecloud-sdk/src/main/resources/META-INF/native-image/io.micronaut.oci/micronaut-oci-sdk/reflect-config.json
Labels: relates-to: graal, type: bug

#268 Rename BOM property
  gradle.properties
Labels: bug, relates-to: build
