Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2023-09, with the labels that each got.

#682 [oracle-cloud] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#690 [oracle-cloud] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#695 test: Close EmbeddedServer
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/AdditionalModelsSerdeSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/DateSerdeSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/EnumSerdeSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/ErrorResponseSerdeSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/ExplicitlySetSerdeSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/MonitoringSerdeSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/VaultSerdeSpec.groovy
Labels: type: improvement

#697 Update versions
  .github/workflows/gradle.yml
  gradle/libs.versions.toml
  oraclecloud-function-http/build.gradle
Labels: type: dependency-upgrade

#698 #696 increase jdk.jar.maxSignatureFileSize system property value to resolve javadoc error
  gradle.properties
Labels: bug

#704 [oracle-cloud] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  buildSrc/src/main/groovy/io.micronaut.build.internal.ocisdk-metadata-published.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#715 [oracle-cloud] Update common files for branch master
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build
