Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2024-04, with the labels that each got.

#867 Fix for the Session Token authentication serde issues
  gradle/libs.versions.toml
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/SessionTokenDeserializer.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/SessionTokenRequestSerializer.java
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/AuthSerdeSpec.groovy
Labels: type: bug

#870 Update versions
  .github/workflows/graalvm-oci.yml
  .github/workflows/gradle.yml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudConfigFileConfigurationPropertiesSpec.groovy
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/serde/SerdeSpecBase.groovy
Labels: type: dependency-upgrade

#876 [oracle-cloud] Update common files for branch 3.8.x
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#882 Make ReadTimeoutException retryable
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClient.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/NettyRule.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/NettyTest.java
Labels: type: bug
