Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2024-07, with the labels that each got.

#940 Add shared, lazy SessionKeySupplier implementation
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/LazySessionKeySupplier.java
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudCoreFactory.java
  oraclecloud-oke-workload-identity/src/main/java/io/micronaut/oraclecloud/oke/workload/identity/OkeWorkloadIdentityFactory.java
Labels: type: improvement

#932 [oracle-cloud] Update common files for branch 4.1.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  gradle/libs.versions.toml
Labels: relates-to: build

#944 remove initialize-at-runtime definitions
  oraclecloud-sdk-processor/src/main/java/io/micronaut/oraclecloud/clients/processor/OracleCloudSdkProcessor.java
Labels: relates-to: graal, type: improvement

#954 add support for filters inside the oci netty client
  gradle/libs.versions.toml
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/ManagedNettyHttpProvider.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyClientProperties.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClient.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClientBuilder.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/OciNettyClientFilter.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/OciServiceInstanceList.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/FirstTestNettyClientFilter.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/ManagedTest.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/NettyTest.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/SecondTestNettyClientFilter.java
  oraclecloud-micrometer/build.gradle
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/OracleCloudMeterRegistryFactory.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/AbstractOracleCloudMeterRegistry.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudMeterRegistry.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudRawMeterRegistry.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilter.java
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudMeterRawRegistrySpec.groovy
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudMeterRegistrySpec.groovy
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/sdk/MockedAuthenticationDetailsProvider.java
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/sdk/OracleCloudSdkMetricsFilterTest.groovy
  oraclecloud-oke-workload-identity/src/main/java/io/micronaut/oraclecloud/oke/workload/identity/MicronautOkeWorkloadIdentityAuthenticationDetailsProviderBuilder.java
  oraclecloud-oke-workload-identity/src/main/java/io/micronaut/oraclecloud/oke/workload/identity/MicronautOkeWorkloadIdentityResourcePrincipalsFederationClient.java
  oraclecloud-oke-workload-identity/src/main/java/io/micronaut/oraclecloud/oke/workload/identity/OkeWorkloadIdentityConfiguration.java
  oraclecloud-oke-workload-identity/src/test/java/io/micronaut/oraclecloud/oke/workload/identity/MicronautOkeWorkloadIdentityResourcePrincipalsFederationClientTest.java
  oraclecloud-sdk-processor/src/main/java/io/micronaut/oraclecloud/clients/processor/OracleCloudSdkProcessor.java
  src/main/docs/guide/micrometer.adoc
Labels: type: enhancement

#950 [oracle-cloud] Update common files for branch 4.2.x
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
