Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2024-02, with the labels that each got.

#801 [oracle-cloud] Update common files for branch master
  .gitignore
Labels: relates-to: build

#802 Improve v1 instance metadata support
  oraclecloud-common/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudMetadataResolver.java
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudMetadataResolverSpec.groovy
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/oracleCloudInstanceMetadata.json
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/v1InstanceMetadata.json
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/v1InstanceNetworkMetadata.json
Labels: type: improvement, type: bug

#805 Support Instance Metadata Service v2
  oraclecloud-common/build.gradle
  oraclecloud-common/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudMetadataConfiguration.java
  oraclecloud-common/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudMetadataResolver.java
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudMetadataConfigurationSpec.groovy
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudMetadataResolverSpec.groovy
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudV2MetadataResolverSpec.groovy
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/instanceMetadata.json
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/instanceNetworkMetadata.json
  oraclecloud-function-http/src/main/java/io/micronaut/oraclecloud/function/http/FnBodyBinder.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/AbstractOracleCloudMeterRegistry.java
Labels: type: improvement

#804 build: managed-ojdbc
  gradle/libs.versions.toml
  oraclecloud-atp-hikari-test/build.gradle
  oraclecloud-atp-ucp-test/build.gradle
  oraclecloud-atp/build.gradle
  oraclecloud-atp/build.gradle.kts
  oraclecloud-bom/build.gradle
Labels: relates-to: build

#808 Improve OCI Config File support
  buildSrc/src/main/groovy/io.micronaut.build.internal.oraclecloud-bom.gradle
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudConfigCondition.java
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudConfigFileConfigurationProperties.java
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudCoreFactory.java
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudConfigFileConfigurationPropertiesSpec.groovy
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudV2MetadataResolverSpec.groovy
  settings.gradle.kts
  src/main/docs/guide/authentication.adoc
Labels: type: improvement

#810 Add support for session token authentication
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudConfigFileConfigurationProperties.java
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudCoreFactory.java
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudConfigFileConfigurationPropertiesSpec.groovy
  oraclecloud-common/src/test/resources/oci_api_key.pem
  oraclecloud-function-http/src/main/java/io/micronaut/oraclecloud/function/http/FnBodyBinder.java
  src/main/docs/guide/authentication.adoc
Labels: type: improvement

#814 [oracle-cloud] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#815 Fix side effect of having metadata configuration mandatory
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/OracleCloudCertificateIntegrationSpec.groovy
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudCoreFactory.java
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudConfigFileConfigurationPropertiesSpec.groovy
  oraclecloud-common/src/test/java/io/micronaut/oraclecloud/core/InstancePrincipalConfigurationTest.java
  oraclecloud-common/src/test/java/io/micronaut/oraclecloud/core/OracleCloudCoreDefaultConfigTest.java
  oraclecloud-common/src/test/java/io/micronaut/oraclecloud/core/OracleCloudCustomAuthConfigTest.java
  oraclecloud-common/src/test/java/io/micronaut/oraclecloud/core/OracleCloudCustomConfigTest.java
  oraclecloud-function-http/src/test/groovy/io/micronaut/oraclecloud/function/http/MockFnHttpServerSpec.groovy
  oraclecloud-function-http/src/test/groovy/io/micronaut/oraclecloud/function/http/ParameterBindingSpec.groovy
  oraclecloud-function-http/src/test/java/io/micronaut/oraclecloud/function/http/ParameterBindingTest.java
  oraclecloud-logging/src/test/groovy/io/micronaut/oraclecloud/logging/OracleCloudLoggingSpec.groovy
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/OracleCloudMeterRegistryFactoryTest.groovy
  oraclecloud-oke-workload-identity/src/test/java/io/micronaut/oraclecloud/oke/workload/identity/OkeWorkloadIdentityConfigurationTest.java
  oraclecloud-sdk-reactor/src/test/java/io/micronaut/oraclecloud/objectstorage/ObjectStorageReactorClientTest.java
  oraclecloud-sdk-rxjava2/src/test/java/io/micronaut/oraclecloud/objectstorage/ObjectStorageRxClientTest.java
  oraclecloud-vault/src/test/groovy/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationSpec.groovy
  test-suite-graal-logging/src/test/java/example/LoggingTest.java
  test-suite-java/src/test/java/example/HikariPoolAtpTest.java
  test-suite-java/src/test/java/example/MicrometerTest.java
  test-suite-java/src/test/java/example/VaultSerializationTest.java
  test-suite-java/src/test/java/example/VaultTest.java
Labels: type: bug

#823 Fix OCI config file configuration
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudConfigFileConfigurationProperties.java
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudCoreFactory.java
  oraclecloud-common/src/test/groovy/io/micronaut/discovery/cloud/OracleCloudConfigFileConfigurationPropertiesSpec.groovy
Labels: type: bug
