Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2024-12, with the labels that each got.

#1021 [oracle-cloud] Update common files for branch 4.3.x
  .github/renovate.json
Labels: relates-to: build

#1037 Remove http client registry from metrics
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/OracleCloudMeterRegistryFactory.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/AbstractOracleCloudMeterRegistry.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudMeterRegistry.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudRawMeterRegistry.java
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudMeterRawRegistrySpec.groovy
Labels: type: bug

#1040 Region provider
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/sdk/AbstractSdkClientFactory.java
  oraclecloud-httpclient-netty/src/test/groovy/io/micronaut/oraclecloud/factory/ObjectStorageFactorySpec.groovy
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/NettyManagedTest.java
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudRawMeterRegistry.java
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/sdk/MonitorRegionProviderSpec.groovy
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/sdk/VaultRegionProviderMock.java
  oraclecloud-sdk-processor/src/main/java/io/micronaut/oraclecloud/clients/processor/OracleCloudSdkProcessor.java
  oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfiguration.java
Labels: type: improvement

#1046 OCI SDK doesn't have service with telemetry-ingestion so we create one
  oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/MonitoringIngestionClient.java
  oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/micrometer/OracleCloudMonitorClientEndpointUsingRegionProviderSpec.groovy
Labels: type: bug
