Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2024-01, with the labels that each got.

#768 Use ObjectMapper from context
  gradle/libs.versions.toml
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/ManagedNettyHttpProvider.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClient.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpResponse.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/OciSdkMicronautSerializer.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/OciSerdeConfiguration.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/OciSerializationConfiguration.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/ManagedTest.java
  oraclecloud-oke-workload-identity/src/main/java/io/micronaut/oraclecloud/oke/workload/identity/MicronautOkeWorkloadIdentityResourcePrincipalsFederationClient.java
Labels: type: improvement

#764 Add links to guides for Micronaut Oracle Cloud
  src/main/docs/guide/authentication.adoc
  src/main/docs/guide/autonomousDatabase.adoc
  src/main/docs/guide/cloudStorage.adoc
  src/main/docs/guide/functions.adoc
  src/main/docs/guide/httpFunctions.adoc
  src/main/docs/guide/micrometer.adoc
  src/main/docs/guide/oracleCloudGuides.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/guide/tracing.adoc
  src/main/docs/guide/vault.adoc
Labels: type: docs

#771 Buffer request even when buffering is disabled
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/NettyTest.java
Labels: bug
