Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2025-10, with the labels that each got.

#1176 Sign requests before buffering
  oraclecloud-httpclient-apache-http-core/src/test/java/io/micronaut/oraclecloud/httpclient/apache/core/ApacheNettyTest.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHttpRequest.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/LegacyNettyManagedTest.java
  test-suite-http-client/build.gradle.kts
  test-suite-http-client/src/main/java/io/micronaut/oraclecloud/httpclient/NettyTest.java
  test-suite-http-client/src/main/java/io/micronaut/oraclecloud/httpclient/SignatureV1.java
Labels: type: bug

#1164 Support client certificate refresh from certificate service
  buildSrc/src/main/groovy/io.micronaut.build.internal.oraclecloud-base.gradle
  gradle/libs.versions.toml
  oraclecloud-certificates/build.gradle
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/OracleCloudCertificationsConfiguration.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/background/OracleCloudCertificationRefresherTask.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/config/CertificateClientContextConfigurer.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/config/CertificateRefreshConfiguration.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/config/OracleCloudCertificateConfiguration.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/config/OracleCloudCertificateProperties.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/deprecated/OracleCloudCertificateBeanCreatedEventListener.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/events/CertificateEvent.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/package-info.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/services/OracleCloudCertificateFetcher.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/services/OracleCloudCertificateService.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/ssl/DelegatedSslContext.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/ssl/OracleCloudCertificateProvider.java
  oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/ssl/OracleCloudSSLContextBuilder.java
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/CertificatesClientBuilderCustomizer.groovy
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/MockAuthenticationDetailsProvider.java
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/ObjectStorageClientBuilderCustomizer.groovy
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/OracleCloudCertificateIntegrationSpec.groovy
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/OracleCloudCertificateMTLSSpec.groovy
  oraclecloud-certificates/src/test/groovy/io/micronaut/oraclecloud/certificates/OracleCloudServiceSpec.groovy
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/OracleCloudClientConfigurationProperties.java
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/sdk/AbstractSdkClientFactory.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/ServiceIdClientConfigurator.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/ServiceIdClientFactory.java
  oraclecloud-sdk-processor/src/main/java/io/micronaut/oraclecloud/clients/processor/OracleCloudSdkProcessor.java
  oraclecloud-serde-processor/src/main/java/io/micronaut/oraclecloud/sdk/processor/SdkImportVisitor.java
  settings.gradle.kts
  src/main/docs/guide/certificates.adoc
  test-suite-http-client/src/main/java/io/micronaut/oraclecloud/httpclient/NettyRule.java
Labels: type: enhancement

#1182 [oracle-cloud] Update common files for branch 5.4.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#1188 [oracle-cloud] Update common files for branch 5.5.x
  .github/workflows/release.yml
Labels: relates-to: build

#1157 [oracle-cloud] Update common files for branch 5.3.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build
