Repository micronaut-projects/micronaut-oracle-cloud, pull requests merged in 2025-08, with the labels that each got.

#1153 Fix encryption SDK serde
  gradle/libs.versions.toml
  oraclecloud-httpclient-apache-http-core/build.gradle
  oraclecloud-httpclient-apache-http-core/src/main/java/io/micronaut/oraclecloud/httpclient/apache/core/serde/OciSerdeConfiguration.java
  oraclecloud-httpclient-apache-http-core/src/main/java/io/micronaut/oraclecloud/httpclient/apache/core/serde/serializers/EncryptionHeaderDeserializer.java
  oraclecloud-httpclient-apache-http-core/src/test/java/io/micronaut/oraclecloud/httpclient/apache/core/ApacheNettyTest.java
  oraclecloud-httpclient-netty/build.gradle
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/OciSdkMicronautSerializer.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/EncryptionHeaderDeserializer.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/EncryptionSdkTest.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/NettyUnmanagedTest.java
  test-suite-http-client/build.gradle.kts
  test-suite-http-client/src/main/java/io/micronaut/oraclecloud/httpclient/NettyTest.java
  test-suite-http-client/src/test/java/io/micronaut/oraclecloud/httpclient/Jersey3Test.java
Labels: type: bug

#1152 OCI SDK 3.70.0
  buildSrc/src/main/groovy/io.micronaut.build.internal.oraclecloud-base.gradle
  gradle.properties
  gradle/libs.versions.toml
  oraclecloud-bom/build.gradle
  oraclecloud-sdk-reactor/build.gradle
  oraclecloud-sdk-rxjava2/build.gradle
  oraclecloud-sdk/build.gradle
  test-suite-http-server-tck-oraclecloud-function-http/src/test/java/io/micronaut/http/server/tck/oraclecloud/function/OracleCloudFunctionServerTestSuite.java
Labels: type: dependency-upgrade

#1161 Buffer even non-streaming body
  oraclecloud-httpclient-apache-http-core/src/test/java/io/micronaut/oraclecloud/httpclient/apache/core/ApacheNettyTest.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/LimitedBufferingBodyHandler.java
  oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHttpResponse.java
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/LegacyNettyManagedTest.java
  test-suite-http-client/src/main/java/io/micronaut/oraclecloud/httpclient/NettyTest.java
  test-suite-http-client/src/test/java/io/micronaut/oraclecloud/httpclient/Jersey3Test.java
Labels: type: bug

#1165 Add @SdkImport annotation to simplify importing an SDK client
  buildSrc/src/main/groovy/io.micronaut.build.internal.ocisdk-metadata-module.gradle
  gradle/libs.versions.toml
  oraclecloud-common/src/main/java/io/micronaut/oraclecloud/core/sdk/SdkImport.java
  oraclecloud-httpclient-netty/build.gradle
  oraclecloud-httpclient-netty/src/test/java/io/micronaut/oraclecloud/httpclient/netty/SdkImportTest.java
  oraclecloud-serde-processor/build.gradle
  oraclecloud-serde-processor/src/main/java/io/micronaut/oraclecloud/httpclient/netty/visitor/SdkImportVisitor.java
  oraclecloud-serde-processor/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  oraclecloud-serde-processor/src/test/groovy/io/micronaut/oraclecloud/httpclient/netty/visitor/SdkImportVisitorSpec.groovy
  settings.gradle.kts
  src/main/docs/guide/httpclient.adoc
Labels: type: enhancement

#1167 separate internal and external public processors
  buildSrc/src/main/groovy/io.micronaut.build.internal.ocisdk-metadata-module.gradle
  oraclecloud-httpclient-netty/build.gradle
  oraclecloud-serde-internal-processor/build.gradle
  oraclecloud-serde-internal-processor/src/main/java/io/micronaut/oraclecloud/httpclient/netty/visitor/OciSdkModelSerdeVisitor.java
  oraclecloud-serde-internal-processor/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  oraclecloud-serde-internal-processor/src/test/groovy/io/micronaut/oraclecloud/httpclient/netty/visitor/OCISdkModelSerdeVisitorSpec.groovy
  oraclecloud-serde-internal-processor/src/test/resources/logback.xml
  oraclecloud-serde-processor/src/main/java/io/micronaut/oraclecloud/sdk/processor/SdkImportVisitor.java
  oraclecloud-serde-processor/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  settings.gradle.kts
Labels: type: improvement
